name: Release

on:

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to Release'
        required: true

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: "Select Xcode 12.4"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "12.4"

      - name: "Setup Git Access"
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github

      - name: "Bump Plugins Version"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          bundle exec rake bump_plugin

      - name: "Bump Version"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          bundle exec rake "bump[${{ github.event.inputs.version }}]"

      - name: "Archive Package"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          bundle exec rake package

      - name: "Release Package"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          bundle exec rake release